global:
  scrape_interval: 5s
  external_labels:
      monitor: 'demo-redisconf19'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'db-redis-exporter'
    static_configs:
      - targets: ['db-redis-exporter:9121']